### ISSUE TITLE
Unrelated question, answered and removed

### ISSUE THREAD

**Issue by cbmeeks** [jacgoudsmit/L-Star#3]
(Unrelated question; answered and removed. JG)

**Comment by jacgoudsmit** [comment]
1) The ~~ operator can be used in two ways: ~~X means sign-extend bit 15,
but X~~ means set all bits. So in those examples it simply sets the pins to
1 and the directions to output. See page 157 and 158 of the Propeller
Manual (v1.2).

2) Setting the value of a pin before setting the direction prevents extra
pulses on the output pin. After a Reset, the OUTA register is reset to 0,
so if I would change the direction first, the pin's output transistors
would go from a situation where they're not pulling the pin high or low, to
a situation where they're pulling the output low until the OUTA bit changes
after the next instruction. By setting the bits in OUTA first, followed by
setting the pin direction to Output, the pin changes from
not-pulling-high-or-low to pulling-low. This is not Propeller-specific or
L-Star specific, it's just a general principle for all situations where an
electronic part can pull a signal low or high or "none of the above"
(commonly referred to as High-Z).

===Jac

**Comment by cbmeeks** [comment]
Yes, that makes sense.

Thanks for the explanation.
