### ISSUE TITLE
A1PIA outputs character when writing to direction register

### ISSUE THREAD

**Issue by jacgoudsmit** [jacgoudsmit/L-Star#4]
The PIA on the Apple-1 has two control bits CRA-2 and CRB-2 that determine whether a write to the corresponding port actually writes data to the port, or writes the direction control register. The emulation assumes that the direction register is fixed, and doesn't heed those two control bits. Since the Woz monitor starts by setting up the direction bits for port B to $7F, that character shows up on the serial output and video driver even though it shouldn't. The emulation should be modified to fix this.

**Comment by cbmeeks** [comment]
Do you know where the source code to the Woz monitor is?  I know it's online but do you know where the source for the binary you are using for L-Star is?  

Shouldn't be too hard to decompile.

**Comment by jacgoudsmit** [comment]
The issue was "fixed" by patching Woz Mon to output the byte to $d013 which has no effect.
A real fix is difficult because it would require that the PIA emulator would know about the system being reset.
